[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip_lint = false

[programs.localnet]
litterbox_v2 = "AX6vgdmqDXRVd3kNwT8Xt7B49GcDTDFR4LwV7caxmZCG"

[programs.devnet]
litterbox_v2 = "AX6vgdmqDXRVd3kNwT8Xt7B49GcDTDFR4LwV7caxmZCG"

[programs.mainnet]
litterbox_v2 = "AX6vgdmqDXRVd3kNwT8Xt7B49GcDTDFR4LwV7caxmZCG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
